#!/usr/bin/env bash












set -e

cd "$(dirname "$0")"
if [ -e ./env/bin/activate ]; then
    source ./env/bin/activate
else
    echo "Creating new venv."
    python3 -m venv env
    source ./env/bin/activate
    pip install -r contrib/deterministic-build/requirements.txt
    pip install -r contrib/deterministic-build/requirements-binaries.txt
    pip install --no-dependencies -e .
    echo "Done creating venv."
fi


DEPS_CHANGED_TIME=$(stat --printf %Y contrib/deterministic-build/requirements.txt)
if [ "$DEPS_CHANGED_TIME" -gt "$(stat --printf %Y env)" ] ; then
    echo "Detected changed requirements.txt. Updating dependencies now..."
    pip install -r contrib/deterministic-build/requirements.txt
    pip install -r contrib/deterministic-build/requirements-binaries.txt
    touch env
    echo "Done updating deps."
fi

./run_405litewallet "$@"
